import type { Metadata } from "next";
import { Inter, Playfair_Display, Sora } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
  display: "swap",
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
  display: "swap",
});

const sora = Sora({
  variable: "--font-sora-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "TickTan Limited",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${playfairDisplay.variable} ${sora.variable} h-full antialiased`}
    >
      <body className={`${inter.className} font-sans min-h-full flex flex-col`}>
        {children}
      </body>
    </html>
  );
}
